# From: https://github.com/ljharb/nvm/pull/8

name: 'Test Suites: take 1'

on: [pull_request, push]

jobs:
  tests:
    name: 'test suites'
    runs-on: ubuntu-latest
    defaults:
      run:
        #shell: 'script -q -e -c "${{ matrix.shell }} {0}"'
        shell: '${{ matrix.shell }} {0}'
    env:
      NVM_DIR: ${{ github.workspace }}

    strategy:
      fail-fast: false
      matrix:
        shell:
          - bash
          #- sh
          #- dash
        suite:
          - fast
          - sourcing
          - slow
          - installation_node
          - installation_iojs
        installer:
          - curl
          - wget
        include:
          - suite: install_script
            shell: bash
            installer: curl
          - suite: install_script
            shell: bash
            installer: wget

    steps:
      - uses: actions/checkout@v3
      - run: sudo ${{ matrix.shell }} --version 2> /dev/null || dpkg -s ${{ matrix.shell }} 2> /dev/null || which ${{ matrix.shell }}
      - run: curl --version
      - run: wget --version
      - uses: ljharb/actions/node/run@main
        name: 'npm install && version checks'
        with:
          node-version: 'lts/*'
          skip-ls-check: true
          shell-command: echo installed
      - run: npm ls urchin
      - run: npm bin
      - run: env
      - run: TERM=xterm-256color SHELL="${{ matrix.shell }}" URCHIN="$(npm bin)/urchin" make test-${{ matrix.shell }}
        env:
          TEST_SUITE: ${{ matrix.suite }}
          NVM_DIR: ${{ env.NVM_DIR }}

  nvm:
    name: 'all test suites, all shells'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
